package webTests;
// Generated by Selenium IDE


import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

    public class seleniumIDE {
        private WebDriver driver;
        private Map<String, Object> vars;
        JavascriptExecutor js;
        @BeforeMethod
        public void setUp() {
            System.setProperty("webdriver.chrome.driver", "drivers/chrome/92/chromedriver.exe");
            driver = new ChromeDriver();
            driver.manage().timeouts().implicitlyWait(60000, TimeUnit.MICROSECONDS);
            js = (JavascriptExecutor) driver;
            vars = new HashMap<String, Object>();
        }
        @AfterMethod
        public void tearDown() {
            driver.quit();
        }
        @Test
        public void cursoMantis() {
            driver.get("https://iterasys.com.br/");
            driver.manage().window().setSize(new Dimension(1500, 1080));
            driver.findElement(By.id("searchtext")).click();
            driver.findElement(By.id("searchtext")).sendKeys("Mantis");
            driver.findElement(By.id("searchtext")).sendKeys(Keys.ENTER);
            assertThat(driver.findElement(By.cssSelector("span.comprar")).getText(), is("MATRICULE-SE  "));
            assertThat(driver.findElement(By.cssSelector("h3")).getText(), is("Cursos › \"Mantis\""));
        }
        @Test
        public void cursoTestLink() {
            driver.get("https://iterasys.com.br/");
            driver.manage().window().setSize(new Dimension(1500, 1080));
            driver.findElement(By.id("searchtext")).click();
            driver.findElement(By.id("searchtext")).sendKeys("testlink");
            driver.findElement(By.id("searchtext")).sendKeys(Keys.ENTER);
            assertThat(driver.findElement(By.cssSelector("h3")).getText(), is("Cursos › \"testlink\""));
        }
    }

